"""add order snapshots and total_amount v2

Revision ID: f719fa76499e
Revises: 0c32c367e59f
Create Date: 2025-11-10 18:05:20.372628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f719fa76499e'
down_revision: Union[str, Sequence[str], None] = '0c32c367e59f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook_events')
    op.alter_column('order_items', 'name_snapshot',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('orders', 'total_amount',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'total_amount',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               nullable=True)
    op.alter_column('order_items', 'name_snapshot',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('webhook_events_pkey'))
    )
    # ### end Alembic commands ###
